# Ball and Brown (1968)

<!-- In this and the following chapter, we cover the first two winners of the Seminal Contributions to Accounting Literature Award: Ball and Brown (1968) and Beaver (1968).1 -->
本章と次章では，「the Seminal Contributions to Accounting Literature Award」の最初の2つの受賞者であるBall and Brown (1968)とBeaver (1968)について説明する。

<!-- Ball and Brown (1968) won the inaugural Seminal Contribution to the Accounting Literature Award with a citation: “No other paper has been cited as often or has played so important a role in the development of accounting research during the past thirty years.” -->
Ball and Brown (1968)は最初に「the Seminal Contribution to the Accounting Literature Award」を受賞し，その受賞理由は「過去30年間において，他のどの論文よりも引用されている論文はなく，会計研究の発展において重要な役割を果たしている」とされている。
<!-- However, Philip Brown (Brown, 1989) recalled in a presentation to the 1989 JAR conference that the paper was rejected by The Accounting Review with the editor indicating a willingness to “reconsider the manuscript if Ray and I wished to cut down the empirical stuff and expand the ‘bridge’ we had tried to build between our paper and the accounting literature.” (Brown, 1989, p. 205) -->
しかし，Philip Brown (Brown, 1989)は1989年のJARカンファレンスでのプレゼンテーションで，この論文がThe Accounting Reviewに拒否されたことを振り返り，編集者が「Rayと私が実証的な部分を削減し，私たちが試みた論文と会計文献との間に構築しようとした『橋』を拡大することを望むなら，原稿を再検討する用意がある」と述べている。

<!-- According to Kothari (2001, p. 113), “Ball and Brown (1968) and Beaver (1968) heralded empirical capital markets research as it is now known.” -->
Kothari (2001, p. 113)によると，「Ball and Brown (1968)とBeaver (1968)は，現在知られている実証的な資本市場研究の到来を告げた」としている。
<!-- Prior to that period, accounting research was a largely theoretical discipline focused on normative research, that is, research concerned with the “right” or “best” way to account for various events and transactions. -->
それ以前の時期には，会計研究は主に理論的な学問であり，規範的研究に焦点を当てていた。つまり，さまざまな事象や取引について「正しい」または「最良の」会計処理方法に関心を持つ研究であった。
<!-- In addition to being normative, accounting theory was largely deductive, meaning that detailed theories were derived from general principles. -->
会計理論は規範的であるだけでなく，主に帰納的であった。つまり，一般的な原則から詳細な理論が導かれていた。

<!-- Beaver (1998) identifies one approach as asking, say, “what properties should the ‘ideal’ net income have?” -->
Beaver (1998)は，あるアプローチを「『理想的な』純利益にはどのような特性があるべきか？」と問うものとして特定している。
<!-- One answer to this question is that accounting income a period should reflect the change in the net present value of cash flows (plus cash distributions) to shareholders during the period. -->
この質問に対する1つの回答は，ある期間の会計収益は，その期間中の株主へのキャッシュフローの現在価値の変化（およびキャッシュ配当）を反映すべきであるというものである。
<!-- But other answers existed. -->
しかし，他の回答も存在した。
<!-- Accounting researchers would start with a set of desired properties and use these to derive the “best” approach to accounting for depreciation of long-lived assets, inventory, or lease assets. -->
会計研究者は，望ましい特性の集合から始め，これらを使用して長期資産の減価償却、棚卸資産、またはリース資産の会計処理の「最良」のアプローチを導き出していた。
<!-- Kothari (2001) points out that there was “little emphasis on the empirical validity” of theory. -->
Kothari (2001)は，理論の「実証的な妥当性」にはほとんど重点が置かれていなかったと指摘している。

<!-- Similar ideas still permeate the thinking of standard-setters, who purport to derive detailed accounting standards from their “conceptual frameworks”, which outline broad definitions of things such as assets and liabilities that standard-setters can supposedly use to derive the correct accounting approach in any given setting. -->
同様の考え方は，基準設定主体の考え方に依然として浸透しており，基準設定主体は「概念フレームワーク」から詳細な会計基準を導出しようとしている。
概念フレームワークは，資産や負債などの広義の定義を概説し，基準設定主体が任意の状況で正しい会計処理方法を導き出すために使用できるとされている。

<!-- However, in the period since Ball and Brown (1968), these approaches have been largely discarded in academic research. -->
しかし，Ball and Brown (1968)以降の時期において，これらのアプローチは学術研究においてほとんど捨てられている。
<!-- A largely normative, theoretical emphasis has been replaced by a positive, empirical one. -->
主に規範的で理論的な重点は，実証的で経験的な重点に置き換えられている。

<!-- This chapter uses Ball and Brown (2019) as a kind of reading guide to Ball and Brown (1968) before considering a replication of Ball and Brown (1968) styled on that provided by Nichols and Wahlen (2004). -->
本章では，Ball and Brown (2019)をBall and Brown (1968)の読み方のガイドとして使用し，Nichols and Wahlen (2004)によるBall and Brown (1968)のレプリケーションを検討する。

:::{.callout-tip}
<!-- The code in this chapter uses the packages listed below. -->
この章のコードは，以下のパッケージを使用する。
<!-- Because we use several packages from the Tidyverse, we save time by using library(tidyverse) to load them in one go.  -->
Tidyverseからいくつかのパッケージを使用するため，`library(tidyverse)`を使用して一括で読み込むことで時間を節約する。
<!-- For instructions on how to set up your computer to use the code found in this book, see Section 1.2.  -->
この書籍で見つかるコードを使用するためのコンピュータのセットアップ方法については，セクション1.2を参照してください。
<!-- Quarto templates for the exercises below are available on GitHub. -->
以下の演習用のQuartoテンプレートはGitHubで入手できる。
:::

```{r}
#| eval: false

library(tidyverse)
library(DBI)
library(farr)
library(dbplyr)     # window_order()
```

## Principal results of Ball and Brown (1968)

<!-- The first two pages of Ball and Brown (1968) address the (then) extant accounting literature. -->
Ball and Brown (1968)の最初の2ページは，（当時の）既存の会計文献について述べている。
<!-- This discussion gives the impression that the (academic) conventional wisdom at that time was that accounting numbers were (more or less) meaningless (“the difference between twenty-seven tables and eight chairs”) and further research was needed to devise more meaningful accounting systems. -->
この議論から，当時の（学術的な）常識は，会計数値は（おおよそ）意味がない（「27のテーブルと8つの椅子の違い」）というものであり，より意味のある会計システムを考案するためにさらなる研究が必要であるという印象を受ける。

<!-- Arguably this notion informs the null hypothesis of Ball and Brown (1968). -->
おそらく，この考え方は，Ball and Brown (1968)の帰無仮説に影響を与えている。
<!-- If accounting numbers are meaningless, then they should bear no relationship to economic decisions made by rational actors. -->
会計数値が意味を持たない場合，それらは合理的な行為者によって行われる経済的な意思決定とは何の関係もないはずである。
<!-- Ball and Brown (1968) seek to test this (null) hypothesis by examining the relationship between security returns and unexpected income changes. -->
Ball and Brown (1968)は，株式リターンと期待外収益変化との関係を調査することで，この（帰無）仮説を検証しようとしている。
<!-- Ball and Brown (1968) argue that “recent developments in capital theory … [justify] selecting the behavior of security prices as an operational test of usefulness.” -->
Ball and Brown (1968)は，「資本理論の最近の発展により，証券価格の挙動を有用性の操作的なテストとして選択することが正当化される」と主張している。

<!-- The evidence provided by Ball and Brown (1968) might not convince critics of the usefulness of adding chairs and tables unless the market is a rational, efficient user of a broader set of information. -->
Ball and Brown (1968)によって提供される証拠は，市場がより広範な情報を合理的かつ効率的に利用する場合にのみ，椅子とテーブルを追加することの有用性を疑問視する批評家を納得させるかもしれない。
<!-- There are accounts for the results of Ball and Brown (1968) that do not rely on such rationality and efficiency. -->
Ball and Brown (1968)の結果には，そのような合理性や効率性に依存しない説明もある。
<!-- First, the market might react to “twenty-seven tables less eight chairs” because it does not know what it is doing. -->
第一に，市場は「27のテーブルから8つの椅子を引いたもの」に反応するかもしれないが，それは何をしているのかわからないためである。
<!-- Second, the market might know that “twenty-seven tables less eight chairs” is meaningless, but has no better information to rely upon. -->
第二に，市場は「27のテーブルから8つの椅子を引いたもの」が意味をなさないことを知っているかもしれないが，それ以上の情報がないために頼ることができない。
<!-- Given the arguments they seek to address, assumptions that the market is (a) efficient and (b) has access to a rich information set beyond earnings seem implicit in the use of security returns in a test of usefulness. -->
彼らが取り組もうとしている議論を考慮すると，株式リターンを使用して有用性のテストを行う際に，市場が（a）効率的であり，（b）収益以外の豊富な情報セットにアクセスできるという仮定は暗黙的に含まれているように思われる。

<!-- Ball and Brown (2019, p.414) identify three main results of Ball and Brown (1968): “The most fundamental result was that accounting earnings and stock returns were correlated. -->
Ball and Brown (2019, p.414)は，Ball and Brown (1968)の3つの主要な結果を次のように特定している。「最も基本的な結果は，会計収益と株価リターンが相関していたことである。
<!-- … Nevertheless, annual accounting earnings lacked timeliness. -->
… それにもかかわらず，年次の会計収益にはタイムリー性が欠けていた。
<!-- … After the earnings announcement month, the API (which cumulated abnormal returns) continued to drift in the same direction.” -->
… 収益発表月の後，API（異常リターンを累積したもの）は同じ方向にドリフトし続けた。」

<!-- Figure 1 of Ball and Brown (1968) depicts the data provided in Table 5 and comprises all three of the principal results flagged by Ball and Brown (2019). -->
Ball and Brown (1968)の図1は，表5に提供されたデータを描いており，Ball and Brown (2019)が指摘した3つの主要な結果すべてを含んでいる。

<!-- The returns reported in Figure 1 of Ball and Brown (1968) are not feasible portfolios because the earnings variables used to form each portfolio at month $-12$ are not reliably available until month $0$ or later. -->
Ball and Brown (1968)の図1に報告されているリターンは，月 $-12$ で各ポートフォリオを形成するために使用される収益変数が，月 $0$ 以降にならないと信頼できないため，実現可能なポートフォリオではない。
<!-- Yet one can posit the existence of a mechanism (e.g., a time machine or a magical genie) that would suffice to make the portfolios notionally feasible. -->
しかし、仮にポートフォリオを理論的に実現可能にするメカニズム（例：タイムマシンや魔法の妖精）が存在すると仮定することはできる。
<!-- For example, if a genie could tell us whether earnings for the upcoming year for each firm will increase or decrease at month $-12$, we could go long on firms expecting positive news, and go short on firms expecting negative news.2  -->
たとえば、もし妖精さんが各企業の翌年の収益が増加するのか減少するのかを， $12$ ヶ月前に教えてくれるとすれば、利益がプラスであるというニュースを期待できる企業の株を買い（ロング）、マイナスとなるニュースを期待する企業の株を売る（ショート）ことが可能になる。
<!-- Note that this hypothetical genie is sparing with the information she provides. -->
この仮想的な妖精さんは，提供する情報を非常に限定的にしている点に注意が必要である。
<!-- For example, we might want further details on how much earnings increased or decreased, but our genie gives us just the sign of the earnings news. -->
たとえば，利益がどれほど増加・減少したのかについてさらに詳細をしりたいかもしれないが，妖精さんは利益ニュースの符号だけを教えてくれる。

<!-- Additionally, we have implicit constraints on the way we can use this information in forming portfolios. -->
さらに，ポートフォリオを形成する際にこの情報を使用する方法には暗黙の制約がある。
<!-- We might do better to adjust the portfolio weights according to other factors, such as size or liquidity, but the portfolios implicit in Figure 1 of Ball and Brown (1968) do not do this. -->
サイズや流動性などの他の要因に応じてポートフォリオのウェイトを調整する方が良いかもしれないが，Ball and Brown (1968)の図1に暗黙的に含まれるポートフォリオはこれを行っていない。
<!-- Nor do the portfolios represented in Figure 1 involve any opportunity to adjust portfolio weights during the year. -->
また，図1に表されているポートフォリオには，年間を通じてポートフォリオのウェイトを調整する機会もない。

<!-- In assessing the relative value of various sources of information, Ball and Brown (1968) consider three approaches to constructing portfolios, which they denote as TI, NI, and II (Ball and Brown (2019) denote II as AI and we follow this notation below). -->
さまざまな情報源の相対的価値を評価する際，Ball and Brown (1968)は， $TI$ ， $NI$ ， $II$ として示される3つのポートフォリオの構築方法を考慮している（Ball and Brown (2019)は $II$ を $AI$ として示しており，以下ではこの表記に従う）。

<!-- Using these metrics, Ball and Brown (1968, p.1)  conclude that “of all the information about an individual firm which becomes available during a year, one-half or more is captured in that year’s income number. -->
これらのメトリクスを使用して，Ball and Brown (1968, p.1) は「1年間に個々の企業に関するすべての情報のうち，半分以上がその年の収益数値に含まれている」と結論づけている。
<!-- … However, the annual income report does not rate highly as a timely medium, since most of its content (about 85 to 90 per cent) is captured by more prompt media which perhaps include interim reports.”3 -->
… ただし，年次の収益報告書はタイムリーな媒体として高く評価されていない。なぜなら，その内容の大部分（約85〜90％）は，中間報告書を含むより迅速な媒体によって把握されているからである。」

<!-- The third principal result is shown in Table 5, where we see that the income surprise is correlated with the API to a statistically significant extent in each month up to two months after the earnings announcement.4 -->
3番目の主要な結果は，表5に示されており，収益サプライズは，収益発表後2ヶ月までの各月において，APIと統計的に有意な程度で相関していることがわかる。

<!-- This result, which later become known as post-earnings announcement drift (or simply PEAD), was troubling to Ball and Brown (1968), who argue that some of it may be explained by “peak-ahead” in the measure of market income and transaction costs causing delays in trade. -->
この結果は，後に収益発表後のドリフト（または単にPEAD）として知られるようになり，Ball and Brown (1968)にとって問題となっていた。彼らは，市場収益の「ピーク・アヘッド」と取引コストによる取引の遅延が一部説明できる可能性があると主張している。
<!-- We study PEAD more closely in Chapter 14. -->
PEADについては，第14章で詳しく検討する。


### 11.1.1 Discussion questions


1. What is the research question of Ball and Brown (1968)? Do you find the paper to be persuasive?

2. What do you notice about the references in Ball and Brown (1968, pp. 177–178)?

3. Given that “the most fundamental result” of Ball and Brown (1968) relates to an association or correlation, is it correct to say that the paper provides no evidence on causal linkages? Does this also mean that Ball and Brown (1968) is a “merely” descriptive paper according to the taxonomy of research papers outlined in Chapter 4. How might the results of Ball and Brown (1968) be represented in a causal diagram assuming that accounting information is meaningful and markets are efficient? Would an alternative causal diagram be assumed by a critic who viewed accounting information as meaningless?

4. Describe how Figure 1 of Ball and Brown (1968) supports each of principal results identified by Ball and Brown (2019).

5. Consider the causal diagrams you created above. Do the results of Ball and Brown (1968) provide more support for one causal diagram than the other?

6. Compare Figure 1 of Ball and Brown (2019) with Figure 1 of BB68. What is common between the two figures? What is different?

7. What does “less their average” mean in the title of Figure 1 of Ball and Brown (2019)? What effect does this have on the plot? (Does it make this plot different from Figure 1 of BB68? Is information lost in the process?)

9. Ball and Brown (2019, p. 418) say “in this replication we address two issues with the BB68 significance tests.” Do you understand the points being made here?

10. Ball and Brown (2019, p. 418) also say “the persistence of PEAD over time is evidence it does not constitute market inefficiency.” What do you make of this argument?

11. What is the minimum amount of information that our hypothetical genie needs to provide to enable formation of the portfolios underlying TI, NI, and II? What are the rules for construction of each of these portfolios?

12. Ball and Brown (1968) observe a ratio of NI to TI of about 0.23. What do we expect this ratio to be? Does this ratio depend on the information content of accounting information?

13. Consider the paragraph in Ball and Brown (2019, p. 418) beginning “an innovation in BB68 was to estimate …”. How do the discussions of these results differ between Ball and Brown (1968) and Ball and Brown (2019)?

14. Consider column (4) of Table 2 of Ball and Brown (2019). Is an equivalent set of numbers reported in BB68? What is the underlying investment strategy associated with this column (this need not be feasible in practice)?

15. Heading 6.3 of Ball and Brown (2019) is “Does ‘useful’ disprove ‘meaningless’?” Do you think that “not meaningless” implies “not useless”? Which questions (or facts) does BB68 address in these terms?
